version: '2'

services:
  sql_server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      SA_PASSWORD: "LaravelUser@123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      MSSQL_TCP_PORT: "1433"
      MSSQL_CERT_FILE: "/certs/server-cert.pem"
      MSSQL_KEY_FILE: "/certs/server-key.pem"
      MSSQL_CA_FILE: "/certs/ca-cert.pem"
    ports:
      - "1433:1433"
    volumes:
    # mount a local project sub directory  to docker
      - ./mssql/data:/var/opt/mssql
    networks:
      - backend

networks:
  backend:
